q=[]
q.append("a")
q.append("b")
q.append("c")
q.append("d")
print("queue",q)
print("is queue empty",len(q)==0)
print("the size of queue",len(q))
item=q.pop(0)
print("the dequeue",item)
item=q.pop(0)
print("the dequeue is",item)
print("the final queue",q)
print("is empty",len(q)==0)
print("len of queue",len(q))
